// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/modules/order_tracking/presentation/view_models/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/config/base_response/base_response.dart' as _i4;
import 'package:flowery/core/services/location_service.dart' as _i8;
import 'package:flowery/modules/order_tracking/domain/entity/home_entity/order_entity.dart'
    as _i7;
import 'package:flowery/modules/order_tracking/domain/entity/home_entity/paginated_orders_entity.dart'
    as _i5;
import 'package:flowery/modules/order_tracking/domain/repo/profile_repo_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderTrackingRepoContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingRepoContract extends _i1.Mock
    implements _i2.OrderTrackingRepoContract {
  MockOrderTrackingRepoContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.PaginatedOrdersEntity>> getOrders({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {#page: page}),
            returnValue:
                _i3.Future<_i4.Result<_i5.PaginatedOrdersEntity>>.value(
                  _i6.dummyValue<_i4.Result<_i5.PaginatedOrdersEntity>>(
                    this,
                    Invocation.method(#getOrders, [], {#page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.PaginatedOrdersEntity>>);

  @override
  _i3.Future<_i4.Result<String>> acceptOrder(_i7.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOrder, [order]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i6.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#acceptOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> startTracking(String? driverId) =>
      (super.noSuchMethod(
            Invocation.method(#startTracking, [driverId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void stopTracking() => super.noSuchMethod(
    Invocation.method(#stopTracking, []),
    returnValueForMissingStub: null,
  );
}
