// Mocks generated by Mockito 5.4.6 from annotations
// in flowery/test/modules/order_tracking/data/repo/order_tracking_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery/config/base_response/base_response.dart' as _i4;
import 'package:flowery/modules/order_tracking/data/data_sources/firestore_data_source.dart'
    as _i8;
import 'package:flowery/modules/order_tracking/data/data_sources/orders_remote_data_sources_contract.dart'
    as _i2;
import 'package:flowery/modules/order_tracking/data/model/driver_profile_response_model.dart'
    as _i7;
import 'package:flowery/modules/order_tracking/data/model/home_response_models/home_respnose_model.dart'
    as _i5;
import 'package:flowery/modules/order_tracking/domain/entity/home_entity/order_entity.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderTrackingRemoteDataSourcesContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderTrackingRemoteDataSourcesContract extends _i1.Mock
    implements _i2.OrderTrackingRemoteDataSourcesContract {
  MockOrderTrackingRemoteDataSourcesContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.HomeResponseModel>> getHomeData({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeData, [], {#page: page}),
            returnValue: _i3.Future<_i4.Result<_i5.HomeResponseModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.HomeResponseModel>>(
                this,
                Invocation.method(#getHomeData, [], {#page: page}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.HomeResponseModel>>);

  @override
  _i3.Future<_i4.Result<_i7.DriverProfileResponseModel>> getDriverProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getDriverProfile, []),
            returnValue:
                _i3.Future<_i4.Result<_i7.DriverProfileResponseModel>>.value(
                  _i6.dummyValue<_i4.Result<_i7.DriverProfileResponseModel>>(
                    this,
                    Invocation.method(#getDriverProfile, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i7.DriverProfileResponseModel>>);

  @override
  _i3.Future<_i4.Result<void>> startOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#startOrder, [orderId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#startOrder, [orderId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [FirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDataSource extends _i1.Mock
    implements _i8.FirestoreDataSource {
  MockFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> updateDriverLocation({
    required String? driverId,
    required double? lat,
    required double? lng,
    required double? accuracy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDriverLocation, [], {
              #driverId: driverId,
              #lat: lat,
              #lng: lng,
              #accuracy: accuracy,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveAcceptedOrder({
    required _i9.OrderEntity? order,
    required _i7.DriverProfileResponseModel? driver,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveAcceptedOrder, [], {
              #order: order,
              #driver: driver,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
